### ISSUE TITLE
Include Support for other languages besides JavaScript

### ISSUE THREAD

**Issue by Stargator** [CodierIO/codier-issues#12]
It seems Codier only supports HTML, CSS, and JavaScript for the frontend creations.

I would like to suggest opening it up so that TypeScript, Dart, CoffeeScript, and other frontend-capable languages can be used.

## Expected Behavior
When you opt to create something for a challenge you can choose a different language than JavaScript to be used as the controller for your logic.

## Current Behavior
Instead, the workspace has JavaScript hardcoded as the language for the controller logic.

**Comment by kenanyusuf** [comment]
Hi @Stargator, thanks for raising this.

Within the JavaScript settings, you will see a handful of other languages that we support. See GIF example:

![a73268eec7d8b10a0cc348d278e58366](https://user-images.githubusercontent.com/9557798/43606293-d55b1c2c-9692-11e8-9e3c-f37c0c3fb496.gif)

Assuming this is what you are looking for, I shall close this issue.

**Comment by Stargator** [comment]
Okay, thanks I didn't catch there were settings there. I also suggested Dart as of the alternatives to JavaScript. And [I'm big on Dart](www.github.com/exercism/dart).
