### ISSUE TITLE
Double history in browser

### ISSUE THREAD

**Issue by ghost** [CodierIO/codier-issues#13]
When you enter the editor view, then it adds the same page twice to the history. I need to click the back button twice because of it.

I had a very familiar issue at work and it's possible, that the iframe causes this. The solution was to not use iframe's src but use window.location=xxx from inside of the iframe.

## Expected Behavior
The page should be added to the history once.

## Current Behavior
The page is added to the history twice.

## Steps to Reproduce
1. Enter editor view
2. Voila!

## Environment
Newest Firefox

**Comment by kenanyusuf** [comment]
@AriInteractive Thanks for submitting this issue - I have tried what you suggested and it seems to have fixed the problem! I will test a little more and if all is well, it will be deployed shortly. Thank you!

**Comment by kenanyusuf** [comment]
Fixed in the latest release.
