### ISSUE TITLE
Login Page is showing password instead of showing *

### ISSUE THREAD

**Issue by kevinhongw** [CodierIO/codier-issues#19]
## Expected Behavior

While logging in the password input type should be "password" instead of "text"

## Current Behavior

The password field is not secured with *. So instead of "********" i will see "password".

## Steps to Reproduce

1. Click Login
2. Click on password field
3. Start typing

## Environment

Browser & Version: Chrome 71
Operating System: MacOS 10.12

**Comment by kenanyusuf** [comment]
Thanks a lot for raising this issue - I have just put out a fix for this.
