### ISSUE TITLE
Editor not loading in Chrome on Android

### ISSUE THREAD

**Issue by mggwxyz** [CodierIO/codier-issues#9]
The page doesn't load when clicking on a solution when using Chrome on an Android device.

## Expected Behavior
Editor should load after solution is selected

## Current Behavior
A blank page is shown after the loading animation ends

## Steps to Reproduce

1. Open the chrome browser android app
2. Navigate to codier.io
3. Click on any solution displayed on the homepage
4. Verify that the page is blank instead of seeing the solution

## Environment

Browser & Version: Chrome
Operating System: Android 8.0.0

**Comment by kenanyusuf** [comment]
Hi @mggwxyz, thanks for submitting this bug. As a temporary solution, on mobile we are redirecting users to an embeddable version of creations. We are working on a mobile version of the editor, but want to give it the time and attention it deserves. Will drop another comment on here once it is complete.
